on:
  workflow_call:

name: Workflow - Build installer

jobs:
  build-installer:
    runs-on: windows-latest
    name: Build Windows installer

    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Install Inno Setup
        run: |
          Invoke-WebRequest -Uri https://jrsoftware.org/download.php/is.exe -OutFile is.exe
          .\is.exe /verysilent
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dyn2py.exe
          path: dist/dyn2py.exe
      - name: Update version number
        run: |
          $regex = Select-String -Path pyproject.toml -Pattern '^version = "((?:\d\.){2}\d)"$'
          $version = $regex.Matches.Groups[1].Value
          (Get-Content dyn2py-installer.iss).Replace("x.x.x",$version) | Set-Content dyn2py-installer.iss
      - name: Build installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" -Qp $(Join-Path $PWD.Path dyn2py-installer.iss)
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: dyn2py-installer.exe
          path: Output/dyn2py-installer.exe
