on:
  workflow_call:

name: Workflow - Build installer

jobs:
  build-installer:
    runs-on: windows-latest
    name: Build Windows installer

    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Install Inno Setup
        run: |
          Invoke-WebRequest -Uri https://jrsoftware.org/download.php/is.exe -OutFile is.exe
          .\is.exe /verysilent
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: dyn2py.exe
      - name: Build
        run: |
          .\dyn2py-installer.ps1
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: dyn2py-installer.exe
          path: Output/dyn2py-installer.exe
