on:
  workflow_call:

name: Workflow - Build exe

jobs:
  build:
    runs-on: windows-latest
    name: Build Windows exe

    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: ${{ vars.PYTHON_VERSION}}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install .[build]
      - name: Build
        run: pyinstaller dyn2py.spec
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: dyn2py.exe
          path: dist/dyn2py.exe
