name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-windows-portable:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install .[build]

      - name: Build
        run: pyinstaller dyn2py.spec

      - uses: actions/upload-artifact@v3
        with:
          name: dyn2py.exe
          path: dist/dyn2py.exe

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: dyn2py.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dyn2py.exe
