on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string

name: Workflow - Test

jobs:
  test:
    name: Run tests
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run tests
        run: python -m unittest discover -v -s ./tests -p "test_*.py"
