name: Build Windows exe and installer

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  # push:

jobs:
  build-exe:
    uses: ./.github/workflows/build-exe.yml
    name: Build Windows exe

  build-installer:
    name: Build Windows installer
    needs: build-exe
    uses: ./.github/workflows/build-installer.yml
